config/routes.rb
Rails.application.routes.draw do
  get 'angular/index'

  get 'ya_copy/index'

  get 'static_pages/yandex'

  # root to: 'ya_copy#index'
  root 'angular#index'
  resources :users
  resources :articles do
    get 'filter_tags', on: :collection
  end

  resources :comments
  resources :sessions, only: [:create, :destroy]
  resources :likes
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes,  as: :subject
  has_and_belongs_to_many :tags
  has_attached_file :picture
  validates_attachment_content_type :picture, :content_type => /^image\/(bmp|gif|jpg|jpeg|png)/
  validates :title, presence: true
  validates :body, presence: true
  validates :picture_file_name, presence:true

  def self.filter_by_user_id(user_id)
    self.where(user_id: user_id)
  end

  def self.filter_by_tag(tag_id)
    joins(:tags).where(tags: {id: tag_id})
  end


  def self.filter_by_date(start_date, end_date)
    where('articles.created_at >= ? and articles.created_at <= ?',
      start_date, end_date)
  end

  def self.sort(kind='desc')
    if kind == 'desc'
      self.order("articles.created_at desc")
    elsif kind == 'likes_desc'
      self.joins("LEFT OUTER JOIN likes ON likes.subject_id = articles.id").group("articles.id").order("count(likes.subject_id) desc")
    elsif kind == 'likes_asc'
      self.joins("LEFT OUTER JOIN likes ON likes.subject_id = articles.id").group("articles.id").order("count(likes.subject_id) asc")
    else
      self.order("articles.created_at asc")
    end
  end

  def first_level_comments
    comments.where('comment_id is null')
  end

  def short_body
    body.split[0..10].join(' ')
  end

  def tags_string=(string)
    names = Tag.parse_tags_string(string)
    self.tags = names.map do |name|
      Tag.find_or_create_by!(name: name)
    end
  end

  def tags_string
    tags.map(&:name).join(', ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    @tags = Tag.all

    article_params = params[:article]

    query = Article.includes(:user)

    unless article_params.blank?
      query = query.sort(article_params[:kind])

      if !article_params[:user_id].blank?
        query = query.filter_by_user_id(article_params[:user_id])
      end

      article_start_date = build_date_from_params("start_date", article_params)
      article_end_date = build_date_from_params("end_date", article_params)

      if !article_params[:tag_id].blank?
        query = query.filter_by_tag(article_params[:tag_id])
      end

      if !article_start_date.blank?
        query = query.filter_by_date(article_start_date, article_end_date)
      end
      @articles = query.paginate(:page => params[:page], :per_page => 5)
    else
      @articles = query.paginate(page: params[:page], :per_page => 5)
    end
	end

  def show
    @article = Article.includes(
      :user,
      comments: [:user, :likes]
    ).find(params[:id])
    @comments = build_comments_tree(@article.comments)
    # @comments = @article.first_level_comments
  end

  def new

  end
  def filter_tags
    names = Tag.parse_tags_string(params[:tags])
    existing_names = Tag.where(name: names).map(&:name)
    new_names = names - existing_names
    render json: new_names
  end
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
      params.require(:article).permit(
        :title, :body, :picture, :user_id, :tags_string
      )
    end

    def build_comments_tree(comments)
      pairs = comments.sort_by(&:created_at).map do |comment|
        [ comment.id, [comment,[],true] ]
      end
      nodes = Hash[pairs]

      nodes.each do |id, value|
        comment, _ = value
        if comment.comment_id
          nodes[comment.comment_id][1] << value
          value[2] = false
        end
      end

      nodes.values.select {|node| node[2] }
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.slim
- comment, children = comment

div.comment

  p id
  p style="color:red" = comment.id
  p = link_to "#{comment.article.title}", article_path(comment.article)
  p = comment.created_at
  p = link_to "#{comment.user.name}", user_path(comment.user)
  img src = comment.user.avatar
  p = comment.body
  p Parent id:  #{comment.comment_id}
  / p = comment.comment_id
  p
    = link_to "Write comment", new_comment_path(comment_id: comment.id, article_id: comment.article)
  p Likes:
  div class="comment_like_counter"
    p = comment.likes.size
  p = link_to 'Like!', likes_path(subject_id: comment.id, subject_type: 'Comment'), method: 'post', remote: true
  div style="padding-left: 60px"
    = render partial: "comment", collection: children

app/views/articles/index.slim
h1 Listing all articles
= link_to "Write new article", new_article_path
br
= link_to "Sort by date desc", articles_path(article: (params[:article] || {}).merge(kind: 'desc'))
br
= link_to "Sort by date asc", articles_path(article: (params[:article] || {}).merge(kind: 'asc'))
br
= link_to "Sort by likes desc", articles_path(article: (params[:article] || {}).merge(kind: 'likes_desc'))
br
= link_to "Sort by likes asc", articles_path(article: (params[:article] || {}).merge(kind: 'likes_asc'))
p Tags:
-@tags.each do |tag|
  =link_to "#{tag.name} |", articles_path(article: (params[:article] || {}).merge(tag_id: tag.id))


br
= form_tag({}, method: 'get')
  - unless params[:article].blank?
    - params[:article].each do |field, value|
      = hidden_field_tag "article[#{field}]", value
  = date_select "article", "start_date"
  = date_select "article", "end_date"
  = submit_tag 'Filter'

table

  - @articles.each do |article|
    tr
      td
        = article.id
    - a = Article.where("articles.id = #{article.id}").select("COUNT(DISTINCT comments.id) as total_comments, COUNT(DISTINCT likes.id) as total_likes, tags.id").joins("LEFT OUTER JOIN comments ON comments.article_id = articles.id").joins(:tags).group("articles.id, tags.id").select('articles.id').joins("LEFT OUTER JOIN likes ON likes.subject_id = articles.id AND likes.subject_type = 'Article'").first


    tr
      td
        h2 = article.title
    tr
      td
        = article.created_at
    tr
      td

        = link_to article.user.name, user_path(article.user)

    tr
      td
        -if current_user?(article.user)
          = link_to "Delete article", article_path(article), method: 'delete'


    tr
      td Comments:
      td = a.total_comments
      td Likes:
      td = a.total_likes
    tr
      td Tags:
      td
        -unless a.tags.empty?
          - a.tags.each do |tag|
            = link_to "#{tag.name} |", articles_path(article: (params[:article] || {}).merge(tag_id: tag.id))
    tr
      td
        img src = article.picture
    tr
      td = article.short_body + "..."


    tr
      td = link_to 'Read', article_path(article)

= will_paginate @articles

app/views/articles/new.slim
h1 New article
= form_for :article, url: articles_path do |f|

  div.field
    = f.label :title
    br
    = f.text_field :title
  div.field
    = f.label :text
    br
    = f.text_area :body
  div.field
    = f.label :tags_string
    br
    = f.text_area :tags_string, placeholder: "Tags separated with coma", class: 'tags-input'
  div.field
    = f.file_field :picture
  div.actions
    = f.submit

p New tags to add:
a.new-tags href='#'

app/views/articles/show.slim
table
  tr
    td
      = link_to 'Back', articles_path
  tr
    td
      h1 = @article.title
  tr
    td
      = link_to "#{@article.user.name}", user_path(@article.user)
  tr
    td
      = @article.created_at
  tr
    td
      img src = @article.picture

  tr
    td = @article.body
  tr
    td
      div id="like" = link_to 'Like!', likes_path(subject_id: @article.id, subject_type: 'Article'), method: 'post', remote: true
    td = link_to 'Write a comment', new_comment_path(article_id: @article.id)
  tr
    td Likes:
    td
      div class="article_like_counter" = @article.likes.size
  tr
    td Comments:
    td = @article.comments.size

- unless @comments.empty?
  = render partial: "comment", collection: @comments