config/routes.rb
Rails.application.routes.draw do
  get 'angular/index'

  get 'ya_copy/index'

  get 'static_pages/yandex'

  # root to: 'ya_copy#index'
  root 'angular#index'
  resources :users
  resources :articles do
    get 'filter_tags', on: :collection
  end

  resources :comments
  resources :sessions, only: [:create, :destroy]
  resources :likes
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :subject, polymorphic: true


  def self.filter_by_user_id(user_id)
    self.where(user_id: user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    query = Like.includes(:user, :subject)

    if !params[:user_id].blank?
      query = query.filter_by_user_id(params[:user_id])
    end

    @likes = query.paginate(:page => params[:page], :per_page => 5)
  end

  def new
  end

  def create
    # byebug
    # unless Like.find_by_user_id_and_subject_type(current_user.id, params[:subject_type])
      @like = Like.new
      @like.user_id = current_user.id
      @like.subject_id = params[:subject_id]
      @like.subject_type = params[:subject_type]
      @like.save!
    # end
      render js: "$('.article_like_counter').html(#{@like.subject.likes.count});"
      # respond_to do |format|
      #   format.html
      #   format.js
      # end
    # if params[:subject_type] == 'Article'
    #   redirect_to Article.find(params[:subject_id])
    # else
    #   redirect_to Article.find(Comment.find(params[:subject_id]).article_id)
    # end
  end

  def show

  end
  private
    def like_params
      params.require(:like).permit(:subject_id, :subject_type, :user_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/create.js.erb
<% if @like.subject_type = 'Article'%>
  $(".article_like_counter").html(<%= @like.subject.likes.count %>);
<% else %>
  $(".comment_like_counter").html(<%= @like.subject.likes.count %>);
<% end %>

// $(".comment_like_counter").html(<%= @like.subject.likes.count %>);

app/views/likes/index.slim
h1 Listing all likes

table
  - @likes.order(created_at: :desc).each do |like|
    tr
      td
         = like.created_at
    tr
      td
        = link_to "#{User.find(like.user_id).name}", user_path(User.find(like.user_id))
    - if like.subject_type == 'Article'
        tr
          td Article title:
          td
            = link_to "#{Article.find(like.subject_id).title}", article_path(Article.find(like.subject_id))
    - else
        tr
          td Comment id:
          td
            = link_to "#{Comment.find(like.subject_id).id}", comment_path(Comment.find(like.subject_id))

= will_paginate @likes