config/routes.rb
Rails.application.routes.draw do
  get 'angular/index'

  get 'ya_copy/index'

  get 'static_pages/yandex'

  # root to: 'ya_copy#index'
  root 'angular#index'
  resources :users
  resources :articles do
    get 'filter_tags', on: :collection
  end

  resources :comments
  resources :sessions, only: [:create, :destroy]
  resources :likes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	has_many :comments
	has_many :likes
	has_many :liked_comments, through: :likes, source: :subject, source_type: 'Comment'
	has_many :liked_articles, through: :likes, source: :subject, source_type: 'Article'
	has_attached_file :avatar
	validates_attachment_content_type :avatar, :content_type => /^image\/(bmp|gif|jpg|jpeg|png)/
	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user,   only: [:edit, :update]
	def index
		@users = User.all.paginate(:page => params[:page], :per_page => 50)
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
  	@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end
	private
	  def user_params
	    params.require(:user).permit(:name, :email, :avatar)
	  end

	  def correct_user
	  	@user = User.find(params[:id])
	  	if !current_user?(@user)
	  		flash.now[:danger] = "You have no power over here"
	  		redirect_to(user_path)
	  	else
	  		flash.now[:success] = "Success!"
	  	end
	  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.slim
h1 Edit your profile

= form_for @user do |f|
	div.field
		=f.label :name
		br
		=f.text_field :name
	div.field
		=f.label :email
		br
		=f.email_field :email
	div.field
		=f.file_field :avatar
	div.actions
		= f.submit

app/views/users/index.slim
h1 Listing all users

table
	- @users.each do |user|
		tr
			td.name = user.name
			td.link = link_to 'Show', user_path(user)
			td.link = link_to 'Sign in', sessions_path(id: user.id), method: 'post'
= will_paginate @users

app/views/users/show.slim
h1 User profile

p Name:
= @user.name
p Email:
= @user.email
br
img src = @user.avatar

table
  tr
    td Articles:
    td = link_to @user.articles.size, articles_path(params.merge(article: {user_id: @user.id}))
  tr
    td Comments:
    td = link_to @user.comments.size, comments_path(params.merge(comment: {user_id: @user.id}))
  tr
    td Likes:
    td = link_to @user.likes.size, likes_path(params.merge(user_id: @user.id))
= link_to 'Edit', edit_user_path(@user)
br
= link_to 'Back', users_path